---
# Setup LAMP Server
- hosts: all
  tasks:
   - name: Install LAMP Server
     become: yes
     apt:
            update_cache: yes
            pkg:
                 - apache2
   - name: Start Apache Service
     become: yes
     service:
            name: apache2
            state: started
            enabled: yes                
